### PR TITLE
Create output.txt

### PR DESCRIPTION
**Pull request by TangBaiFeng**
Coverage Test

### CODE REVIEW

**Review by claesmk — COMMENTED** [review]
Why do you want to commit the output from a code coverage report?

**Comment by TangBaiFeng** [comment]
Sorry I saw this on the front page and didn't know if it was just for the first assignment or not 

Pull Request Requirements
All pull requests much attach output from pytest showing all test cases passed along with the coverage report or pull request will be rejected.

**Comment by claesmk** [comment]
It's OK to cut and paste the output of pytest into the description / comments.  You don't need to commit it as a new file.  I don't see any changes to add your slogan.  I also don't see that you have created an issue.  That is what is required for sprint-1

**Comment by claesmk** [comment]
[Here](https://github.com/NCATComp410/comp410_spring_2022/pull/27) is an example pull request for sprint-1

**Pull request closed without merging**
