### PR TITLE
Testing phone number code

### PR DESCRIPTION
**Pull request by npollard-TBX**

### CODE REVIEW

**Review by claesmk — CHANGES_REQUESTED** [review]
The code looks ok, however please add some unit test cases, especially for the case where you will match 10 digits in the [unit-test file ](https://github.com/NCATComp410/comp410_spring_2022/blob/e7f3c0ab20b0200dff0de59b9a165ae81b4814fe/test_pii_data.py#L38) test_pii_data.py

**Comment by claesmk** [comment]
@npollard-TBX please also remember to request a review from someone on your team

**Review by rldejournett1 — APPROVED** [review]
Add your test case for the phone number in test_pii_data.py

**Comment by npollard-TBX** [comment]
Added a test case for the 10 digits

**Review by claesmk — APPROVED** [review]
The code looks fine but please also add some test cases in test

**Pull request merged**
