### PR TITLE
Wall e has_email function

### PR DESCRIPTION
**Pull request by kaylaqhenry**

### CODE REVIEW

**Review by claesmk — COMMENTED** [review]
It looks like you are checking in hidden visual studio workspace files. It would probably be a good idea to have some office hours to sort this out.  What time would work for you?

**Comment by kaylaqhenry** [comment]
Can it be viewed now?

**Comment by claesmk** [comment]
You have some conflicts that need to be resolved and you are still checking in the .vs files.  Probably you clicked "stage all" at some point and that brought in these files.  Do you want me to delete them from your fork for you?

**Comment by kaylaqhenry** [comment]
yes please

**Review by TangBaiFeng — COMMENTED** [review]
@claesmk Is it an issue to have IDE dot files added to the repo? I don't know why they got commited when they are in the gitignore

**Comment by kaylaqhenry** [comment]
Don't i have to merge not to have a conflict?

**Comment by claesmk** [comment]
My guess is that @kaylaqhenry had an older version of .gitignore which did not have the .vs exclusion and then probably clicked stage all which grabbed the .vs files

**Review by TangBaiFeng — COMMENTED** [review]
Misclick on indent

**Review by TangBaiFeng — APPROVED** [review]
It was just indent error on function

**Review by claesmk — APPROVED** [review]
Looks good - I deleted the .vs for you

**Pull request merged**
