### PR TITLE
Wall e Anonymized Email Address

### PR DESCRIPTION
**Pull request by kaylaqhenry**

### CODE REVIEW

**Comment by claesmk** [comment]
Were you getting an error like [this](https://docs.microsoft.com/en-us/visualstudio/version-control/git-resolve-conflicts?view=vs-2022)?  You have some merge conflicts and there shouldn't be any changes in .github/workflows/python-app.yml

I'll try to fix these for you in your branch

**Comment by kaylaqhenry** [comment]
yes, I
 recieved that error.

**Review by claesmk — APPROVED** [review]
Looks OK now.  I fixed a couple of errors for you.  I also resolved several PEP warnings which makes it easier for me to see the overall health of each file.  Please have one more person review then you can merge

**Review by lamerritt1 — APPROVED** [review]
Looks good to me.

**Pull request merged**
