### PR TITLE
Implemented has_email() and has_ssn()

### PR DESCRIPTION
**Pull request by Jazmineox**

### CODE REVIEW

**Comment by claesmk** [comment]
Did you create an issue to go with this pull request?  I don't see it in open [issues](https://github.com/NCATComp410/comp410_spring_2022/issues)

**Review by claesmk — APPROVED** [review]
Looks OK, however, you could consider adding some negative test cases in the future, perhaps in sprint3

**Comment by Jazmineox** [comment]
No, I forgot to do that but I will go do it now.

**Review by rldejournett1 — COMMENTED** [review]
Code looks good, In test_pii_data.py for your has email function you test cased 'user@doamin.com' did you mean 'user@domain.com' or should any ''@' case . com' should work?

**Review by rldejournett1 — APPROVED** [review]

**Pull request merged**
