### PR TITLE
Phone num anon

### PR DESCRIPTION
**Pull request by DPrice29**
Adding test cases to phone number anon

### CODE REVIEW

**Comment by claesmk** [comment]
@DPrice29 your [phone_num_anon](https://github.com/DPrice29/comp410_spring_2022/tree/phone_num_anon) branch was behind bug_smashers so I updated that for you.  I don't see your phone number code in your branch.  You also do not want to merge into NCATComp410:main, you want to merge into bug_smashers, but you won't be able to change that until your phone_num_anon branch has your code in it.

**Comment by DPrice29** [comment]
> @DPrice29 your [phone_num_anon](https://github.com/DPrice29/comp410_spring_2022/tree/phone_num_anon) branch was behind bug_smashers so I updated that for you. I don't see your phone number code in your branch. You also do not want to merge into NCATComp410:main, you want to merge into bug_smashers, but you won't be able to change that until your phone_num_anon branch has your code in it.

Before I made my pr I renamed my branch using these commands. I pushed my changes after your comment, so I see my code in the files changed now but I'm not sure how to redirect the merge to my team branch.

 % git branch -m phone_num_anon
 % git push origin -u phone_num_anon
Enumerating objects: 38, done.
Counting objects: 100% (38/38), done.
Delta compression using up to 8 threads
Compressing objects: 100% (12/12), done.
Writing objects: 100% (23/23), 4.53 KiB | 4.53 MiB/s, done.
Total 23 (delta 16), reused 18 (delta 11)
remote: Resolving deltas: 100% (16/16), completed with 7 local objects.
remote: 
remote: Create a pull request for 'phone_num_anon' on GitHub by visiting:
remote:      https://github.com/DPrice29/comp410_spring_2022/pull/new/phone_num_anon
remote: 
To https://github.com/DPrice29/comp410_spring_2022.git
 * [new branch]      phone_num_anon -> phone_num_anon
Branch 'phone_num_anon' set up to track remote branch 'phone_num_anon' from 'origin'.

**Comment by claesmk** [comment]
If you can cut/paste your new code into the comments here I'll try to sort out what happened.

**Review by wjbush — APPROVED** [review]
It appears to me the correct changes were fixed as far as the phone number and merging to the bug smashers branch is concerned so I'll approve.

**Review by claesmk — APPROVED** [review]
I believe I sorted out all the merge conflicts correctly

**Pull request merged**
