### PR TITLE
Implemented IPv4  fixed

### PR DESCRIPTION
**Pull request by truejv**

### CODE REVIEW

**Comment by claesmk** [comment]
You still have this going into the main branch - you want it to go into bug_smashers.  You can edit this pull request and change the base branch from main to bug_smashers. 
image

**Comment by truejv** [comment]
I got it this time. Thank you for the help.

**Review by claesmk — CHANGES_REQUESTED** [review]
Something like 1.1.1.1 could also be a valid address too - how about a regex like this?
```
\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}
```
While this would match things which are not valid IPv4 addresses per RFC it could be an easy way to match any potential PII

**Review by claesmk — APPROVED** [review]
Looks good - please have someone else on your team review and then you can merge

**Review by wjbush — APPROVED** [review]
I've reviewed your changes/implementations to the IPv4 section and approve your Pull Request

**Pull request merged**
