### PR TITLE
implemented has_credit_card function

### PR DESCRIPTION
**Pull request by kqchristmas**

### CODE REVIEW

**Comment by claesmk** [comment]
You are trying to merge the code_repeat branch into the main branch.  You don't want to do that.  Did you push your work to your [fork](https://github.com/kqchristmas/comp410_spring_2022)? I don't see anything there.

**Comment by kqchristmas** [comment]
> You are trying to merge the code_repeat branch into the main branch. You don't want to do that. Did you push your work to your [fork](https://github.com/kqchristmas/comp410_spring_2022)? I don't see anything there.

I tried to merge into code_repeat branch. I am using Visual Studios. My origin isn't my fork on VS. I don't know how to change it.

**Review by kacoates — APPROVED** [review]
Reviewed

**Comment by claesmk** [comment]
You can either change the remote to your fork in VScode by clicking the ... in the source code window, manage remotes.  Or, the easiest way is to simply clone your fork again to a different directory.  If you do that origin is automatically initialized to your fork.

**Comment by kqchristmas** [comment]
I attempted both, but it didn't initialize to my fork. My remote folders aren't separated in git repository.

**Pull request closed without merging**
