### PR TITLE
Anonymize phone number

### PR DESCRIPTION
**Pull request by npollard-TBX**

### CODE REVIEW

**Comment by claesmk** [comment]
You removed some code when you modified the regex to anonymize phone number which caused the unit-test to fail.  I fixed this for you.

image

**Review by claesmk — APPROVED** [review]
Looks ok - I fixed the regex for you so the unit-tests now pass

**Review by taidoan2k — COMMENTED** [review]
looks good

**Comment by znhinson** [comment]
looks good

**Review by znhinson — COMMENTED** [review]
looks good

**Pull request merged**
