### PR TITLE
Completed has_CC, has_phone, has_SSN

### PR DESCRIPTION
**Pull request by TangBaiFeng**
Is this an improvement compared to #72 ?

### CODE REVIEW

**Comment by claesmk** [comment]
The code looks great, however, I want to make sure the assignment was clear since you have done more work than you needed to.  The intent of the [assignment](https://github.com/orgs/NCATComp410/teams/comp410spring2022class/discussions/9) was for EACH person on the team to implement ONE has_ function.  In this pull request you've implemented three has_ functions.  

Also, multiple has_ functions should not be implemented with a single pull request, they should be broken up into individual pull requests.

It looks like you have an [issue](https://github.com/NCATComp410/comp410_spring_2022/issues/71) open for has_ipv6() - are you planning to implement that.

Please pick ONE has_ function to implement and create an issue for that has_ function and submit a pull request.

**Comment by TangBaiFeng** [comment]
Our team has 5 members (including myself) and 9 functions need to be implemented, so I thought some people had to double up on functions. The 3 I did were all about the same which was why I thought  it would be fine (number's dash number's dash).

 I wasn't planning on doing ipv6, it was just a question that came up when we had our group meeting

**Comment by claesmk** [comment]
OK thanks for the explanation and for agreeing to do the extra work.  I will approve the pull request, however, in the future please limit the pull request to a single issue. Please assign the team member who will implement ipv6 to that issue.

**Review by claesmk — APPROVED** [review]
The code looks good and unit tests are passing.  As we discussed, in the future, please limit pull requests to the content of a single issue. 

Please have one more person from your team review this pull request.  After that is done the merge option will be enabled and you can merge your pull request

**Review by kaylaqhenry — APPROVED** [review]

**Pull request merged**
